/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인 사용자 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 내 프로필 수정 (모든 필드 optional, 빈 객체 = no-op) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        role?: string;
                        dept?: string;
                        initials?: string;
                        color?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트 목록 */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["StatusKey"];
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        /** 프로젝트 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 프로젝트 단건 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 프로젝트 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 태스크 목록 */
        get: {
            parameters: {
                query?: {
                    projectId?: string;
                    assigneeId?: string;
                    status?: components["schemas"]["StatusKey"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
            };
        };
        put?: never;
        /** 태스크 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 태스크 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 태스크 부분 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 단일 태스크 의존성 그래프 (선후 관계) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            predecessors: components["schemas"]["TaskDependency"][];
                            successors: components["schemas"]["TaskDependency"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 의존성 생성 (사이클 검증, FS 검증) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        successorId: string;
                        type?: components["schemas"]["DependencyType"];
                        /** @default 0 */
                        lagDays?: number;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDependency"];
                    };
                };
                /** @description Cycle or schedule violation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/dependencies/{depId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                depId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 의존성 제거 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    depId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gantt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 포트폴리오 간트 조회 (cross-project) */
        get: {
            parameters: {
                query?: {
                    projectId?: string;
                    assigneeId?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GanttResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gantt/by-assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 담당자별 그룹 + 충돌 카운트 (Phase 3 전체, Phase 1 최소 그룹) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GanttByAssignee"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이슈 목록 */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["IssueStatus"];
                    prio?: components["schemas"]["IssuePrio"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Issue"][];
                    };
                };
            };
        };
        put?: never;
        /** 이슈 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IssueCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Issue"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 주간 보고 자동 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        periodStart: string;
                        /** Format: date */
                        periodEnd: string;
                        scopeIds: string[];
                        /** @enum {string} */
                        tone?: "exec" | "team" | "casual";
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 월간 보고 자동 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        year: number;
                        month: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 리포트 이메일 발송 큐 적재 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        recipients: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            queued: number;
                            recipients: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 자유 응답 생성 (스트리밍 가능) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        prompt: string;
                        context?: {
                            [key: string]: unknown;
                        };
                        /** @default false */
                        stream?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK (non-streaming) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            text?: string;
                            citations?: {
                                /** @enum {string} */
                                kind?: "task" | "doc" | "message" | "issue";
                                id?: string;
                            }[];
                        };
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/extract-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회의록/이메일 → 액션 아이템 추출 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        source: "meeting" | "email" | "voice" | "notion" | "csv";
                        content: string;
                        /** @default 0.7 */
                        threshold?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExtractedAction"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 등록된 LLM 연결 목록 (관리자) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmConnection"][];
                    };
                };
            };
        };
        put?: never;
        /** LLM 연결 등록 (관리자) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmConnectionInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmConnection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm-connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** LLM 연결 삭제 (관리자, 기본/활성 제외) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** LLM 연결 수정 (관리자) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmConnectionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmConnection"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/llm-connections/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LLM 연결을 활성 기본값으로 설정 (관리자) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmConnection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm-connections/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LLM 연결 핑 테스트 (관리자) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            latencyMs?: number;
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/realtime/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events 스트림 (단방향 푸시) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE 스트림 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 알림 목록 */
        get: {
            parameters: {
                query?: {
                    unread?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 알림 단건 읽음 처리 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 알림 일괄 읽음 처리 (본인 모든 미읽음을 읽음으로)
         * @description 본인의 모든 미읽음 알림을 일괄 읽음 처리. 멱등(idempotent).
         *     요청 본문 없음. 응답에 갱신된 건수를 반환.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 읽음으로 갱신된 알림 수 */
                            updated: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이슈 상태 전이 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["IssueStatus"];
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Issue"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Approval"][];
                    };
                };
            };
        };
        put?: never;
        /** 결재 요청 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApprovalCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Approval"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결재 의사 결정 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "approved" | "rejected";
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Approval"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CRM 고객 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"][];
                    };
                };
            };
        };
        put?: never;
        /** CRM 고객 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 일정 목록 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"][];
                    };
                };
            };
        };
        put?: never;
        /** 일정 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리소스 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 리소스 예약 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResourceBooking"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문서 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Doc"][];
                    };
                };
            };
        };
        put?: never;
        /** 문서 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        content?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Doc"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 채팅 채널 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 채팅 메시지 전송 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 조직 단위 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrgUnit"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 구성원 초대 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        orgUnitId: string;
                        role: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 폐기 (멱등)
         * @description 지정된 tokenId 의 폐기를 요청한다. 본 단계는 audit 로그만 기록하며,
         *     실제 블록리스트 영속화는 후속 작업 (Prisma RevokedToken 모델 + auth 플러그인 검사).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tokenId: string;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            revoked: boolean;
                            tokenId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서비스 헬스체크 (Public)
         * @description 인증 불필요. 인프라/모니터링용 liveness 엔드포인트.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                            /** @description 가동 시간(초) */
                            uptime?: number;
                            version?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 태스크 코멘트 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        /** 태스크 코멘트 추가 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 이슈 코멘트 목록 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        /** 이슈 코멘트 추가 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        StatusKey: "todo" | "doing" | "review" | "done" | "blocked";
        User: {
            id: string;
            name: string;
            role: string;
            dept: string;
            initials: string;
            color: string;
            /** Format: email */
            email?: string;
            bio?: string;
            userStatus?: string;
        };
        Project: {
            id: string;
            name: string;
            code: string;
            color: string;
            progress: number;
            status: components["schemas"]["StatusKey"];
            /** Format: date */
            due: string | null;
            budget?: number | null;
            members: string[];
            tasks: {
                total: number;
                done: number;
            };
        };
        ProjectCreate: {
            name: string;
            code: string;
            color?: string;
            /** Format: date */
            due?: string;
            budget?: number;
        };
        ProjectPatch: {
            name?: string;
            progress?: number;
            status?: components["schemas"]["StatusKey"];
            /** Format: date */
            due?: string;
            budget?: number;
        };
        Task: {
            id: string;
            title: string;
            status: components["schemas"]["StatusKey"];
            proj: string;
            assignee: string;
            due: string;
            /** @enum {string} */
            priority: "high" | "med" | "low";
            tags: string[];
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            parentTaskId?: string | null;
            kind?: components["schemas"]["TaskKind"];
            progress?: number;
        };
        TaskCreate: {
            title: string;
            proj: string;
            assignee: string;
            /** Format: date */
            due?: string;
            /** @enum {string} */
            priority?: "high" | "med" | "low";
        };
        TaskPatch: {
            title?: string;
            status?: components["schemas"]["StatusKey"];
            assignee?: string;
            /** Format: date */
            due?: string;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            kind?: components["schemas"]["TaskKind"];
            progress?: number;
        };
        /** @enum {string} */
        TaskKind: "task" | "milestone" | "summary";
        /** @enum {string} */
        DependencyType: "FS" | "SS" | "FF" | "SF";
        TaskDependency: {
            id: string;
            predecessorId: string;
            successorId: string;
            type: components["schemas"]["DependencyType"];
            lagDays: number;
            /** Format: date-time */
            createdAt?: string;
        };
        GanttTask: {
            id: string;
            title: string;
            kind: components["schemas"]["TaskKind"];
            projectId: string;
            projectColor?: string;
            assigneeId?: string | null;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            progress: number;
            status: components["schemas"]["StatusKey"];
            /** @enum {string} */
            priority: "high" | "med" | "low";
        };
        GanttResponse: {
            range?: {
                /** Format: date */
                from?: string;
                /** Format: date */
                to?: string;
            };
            tasks: components["schemas"]["GanttTask"][];
            dependencies: components["schemas"]["TaskDependency"][];
        };
        GanttByAssignee: {
            groups: {
                assigneeId: string | null;
                assigneeName?: string | null;
                tasks: components["schemas"]["GanttTask"][];
                conflictCount?: number;
            }[];
        };
        /** @enum {string} */
        IssueSev: "critical" | "high" | "med" | "low";
        /** @enum {string} */
        IssuePrio: "P0" | "P1" | "P2" | "P3";
        /** @enum {string} */
        IssueStatus: "open" | "in-progress" | "in-review" | "resolved";
        Issue: {
            id: string;
            title: string;
            proj: string;
            projColor: string;
            sev: components["schemas"]["IssueSev"];
            prio: components["schemas"]["IssuePrio"];
            status: components["schemas"]["IssueStatus"];
            assignee: string;
            reporter: string;
            tags: string[];
            created: string;
            sla: string;
            slaPct: number;
            comments: number;
            linked: number;
            resolved?: boolean;
        };
        Report: {
            id: string;
            /** @enum {string} */
            kind: "weekly" | "monthly";
            /** Format: date */
            periodStart: string;
            /** Format: date */
            periodEnd: string;
            /** Format: date-time */
            generatedAt: string;
            author?: string;
            tldr?: string;
            kpis?: {
                label?: string;
                value?: string;
                delta?: string;
                /** @enum {string} */
                dir?: "up" | "down" | "flat";
            }[];
            sections: {
                heading?: string;
                body?: string;
                citations?: {
                    kind?: string;
                    id?: string;
                    label?: string;
                }[];
            }[];
        };
        ExtractedAction: {
            title: string;
            assignee: string;
            /** Format: date */
            due?: string;
            /** @enum {string} */
            priority?: "high" | "med" | "low";
            confidence: number;
            sourceQuote?: string;
        };
        /** @enum {string} */
        LlmKind: "lmstudio" | "ollama" | "openai" | "anthropic" | "custom_openai_compat";
        LlmConnection: {
            id: string;
            name: string;
            kind: components["schemas"]["LlmKind"];
            baseUrl: string;
            model: string;
            hasApiKey: boolean;
            isActive: boolean;
            isDefault: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LlmConnectionInput: {
            name: string;
            kind: components["schemas"]["LlmKind"];
            /** Format: uri */
            baseUrl: string;
            model: string;
            apiKey?: string | null;
        };
        Notification: {
            id: string;
            /** @enum {string} */
            kind: "mention" | "sla" | "ai" | "system" | "comment";
            title: string;
            body?: string;
            actor?: string;
            /** Format: date-time */
            time: string;
            read: boolean;
            href?: string;
        };
        RealtimeEvent: components["schemas"]["RealtimeNotification"] | components["schemas"]["RealtimeActivity"] | components["schemas"]["RealtimePresence"] | components["schemas"]["RealtimeChat"];
        RealtimeNotification: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "RealtimeNotification";
            payload: components["schemas"]["Notification"];
        };
        RealtimeActivity: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "RealtimeActivity";
            payload: {
                who?: string;
                what?: string;
                target?: string;
                verb?: string;
                time?: string;
                proj?: string;
                kind?: string;
            };
        };
        RealtimePresence: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "RealtimePresence";
            payload: {
                userId?: string;
                online?: boolean;
                /** Format: date-time */
                lastSeen?: string;
            };
        };
        RealtimeChat: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "RealtimeChat";
            payload: {
                channelId?: string;
                messageId?: string;
                authorId?: string;
                text?: string;
                /** Format: date-time */
                time?: string;
            };
        };
        Approval: {
            id: string;
            title: string;
            requester: string;
            approver: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "cancelled";
            amount?: number;
            reason?: string;
            /** Format: date-time */
            decidedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ApprovalCreate: {
            title: string;
            approver: string;
            amount?: number;
            reason?: string;
            attachments?: string[];
        };
        Client: {
            id: string;
            name: string;
            contact?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            industry?: string;
            ownerId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ClientCreate: {
            name: string;
            contact?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            industry?: string;
        };
        Event: {
            id: string;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location?: string;
            attendees: string[];
            resourceId?: string;
            /** @enum {string} */
            source: "internal" | "google" | "outlook";
        };
        EventCreate: {
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location?: string;
            attendees?: string[];
            resourceId?: string;
        };
        Resource: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "room" | "equipment";
            capacity?: number;
            location?: string;
        };
        ResourceBooking: {
            resourceId: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            bookedBy: string;
        };
        Doc: {
            id: string;
            title: string;
            ownerId: string;
            /** Format: date-time */
            updatedAt: string;
            preview?: string;
        };
        Channel: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "public" | "private" | "dm";
            members: string[];
        };
        OrgUnit: {
            id: string;
            name: string;
            parentId: string | null;
            members: string[];
        };
        IssueCreate: {
            title: string;
            proj: string;
            assignee: string;
            reporter: string;
            sev: components["schemas"]["IssueSev"];
            prio: components["schemas"]["IssuePrio"];
            tags?: string[];
        };
        Comment: {
            id: string;
            body: string;
            author: {
                id: string;
                name: string;
            };
            /** Format: date-time */
            createdAt: string;
        };
        CommentCreate: {
            body: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
