// AUTO-GENERATED by scripts/openapi-to-zod.mjs — DO NOT EDIT.
// Source: ../all-flow-frontend/openapi.yaml
// Run `pnpm openapi:gen` to regenerate. `pnpm openapi:check` validates drift.

import { z } from 'zod';

export const StatusKey = z.enum(["todo", "doing", "review", "done", "blocked"]);
export type StatusKey = z.infer<typeof StatusKey>;

export const User = z.object({
  "id": z.string(),
  "name": z.string(),
  "role": z.string(),
  "dept": z.string(),
  "initials": z.string(),
  "color": z.string(),
  "email": z.string().email().optional()
});
export type User = z.infer<typeof User>;

export const Project = z.object({
  "id": z.string(),
  "name": z.string(),
  "code": z.string(),
  "color": z.string(),
  "progress": z.number().int().min(0).max(100),
  "status": StatusKey,
  "due": z.string(),
  "members": z.array(z.string()),
  "tasks": z.object({
  "total": z.number().int(),
  "done": z.number().int()
})
});
export type Project = z.infer<typeof Project>;

export const ProjectCreate = z.object({
  "name": z.string(),
  "code": z.string(),
  "color": z.string().optional(),
  "due": z.string().optional()
});
export type ProjectCreate = z.infer<typeof ProjectCreate>;

export const ProjectPatch = z.object({
  "name": z.string().optional(),
  "progress": z.number().int().optional(),
  "status": StatusKey.optional(),
  "due": z.string().optional()
});
export type ProjectPatch = z.infer<typeof ProjectPatch>;

export const Task = z.object({
  "id": z.string(),
  "title": z.string(),
  "status": StatusKey,
  "proj": z.string(),
  "assignee": z.string(),
  "due": z.string(),
  "priority": z.enum(["high", "med", "low"]),
  "tags": z.array(z.string())
});
export type Task = z.infer<typeof Task>;

export const TaskCreate = z.object({
  "title": z.string(),
  "proj": z.string(),
  "assignee": z.string(),
  "due": z.string().optional(),
  "priority": z.enum(["high", "med", "low"]).optional()
});
export type TaskCreate = z.infer<typeof TaskCreate>;

export const TaskPatch = z.object({
  "title": z.string().optional(),
  "status": StatusKey.optional(),
  "assignee": z.string().optional(),
  "due": z.string().optional()
});
export type TaskPatch = z.infer<typeof TaskPatch>;

export const IssueSev = z.enum(["critical", "high", "med", "low"]);
export type IssueSev = z.infer<typeof IssueSev>;

export const IssuePrio = z.enum(["P0", "P1", "P2", "P3"]);
export type IssuePrio = z.infer<typeof IssuePrio>;

export const IssueStatus = z.enum(["open", "in-progress", "in-review", "resolved"]);
export type IssueStatus = z.infer<typeof IssueStatus>;

export const Issue = z.object({
  "id": z.string(),
  "title": z.string(),
  "proj": z.string(),
  "projColor": z.string(),
  "sev": IssueSev,
  "prio": IssuePrio,
  "status": IssueStatus,
  "assignee": z.string(),
  "reporter": z.string(),
  "tags": z.array(z.string()),
  "created": z.string(),
  "sla": z.string(),
  "slaPct": z.number().int(),
  "comments": z.number().int(),
  "linked": z.number().int(),
  "resolved": z.boolean().optional()
});
export type Issue = z.infer<typeof Issue>;

export const Report = z.object({
  "id": z.string(),
  "kind": z.enum(["weekly", "monthly"]),
  "periodStart": z.string(),
  "periodEnd": z.string(),
  "generatedAt": z.string(),
  "author": z.string().optional(),
  "tldr": z.string().optional(),
  "kpis": z.array(z.object({
  "label": z.string().optional(),
  "value": z.string().optional(),
  "delta": z.string().optional(),
  "dir": z.enum(["up", "down", "flat"]).optional()
})).optional(),
  "sections": z.array(z.object({
  "heading": z.string().optional(),
  "body": z.string().optional(),
  "citations": z.array(z.object({
  "kind": z.string().optional(),
  "id": z.string().optional(),
  "label": z.string().optional()
})).optional()
}))
});
export type Report = z.infer<typeof Report>;

export const ExtractedAction = z.object({
  "title": z.string(),
  "assignee": z.string(),
  "due": z.string().optional(),
  "priority": z.enum(["high", "med", "low"]).optional(),
  "confidence": z.number().min(0).max(1),
  "sourceQuote": z.string().optional()
});
export type ExtractedAction = z.infer<typeof ExtractedAction>;

export const Notification = z.object({
  "id": z.string(),
  "kind": z.enum(["mention", "sla", "ai", "system", "comment"]),
  "title": z.string(),
  "body": z.string().optional(),
  "actor": z.string().optional(),
  "time": z.string(),
  "read": z.boolean(),
  "href": z.string().optional()
});
export type Notification = z.infer<typeof Notification>;

export const RealtimeNotification = z.object({
  "type": z.enum(["notification"]),
  "payload": Notification
});
export type RealtimeNotification = z.infer<typeof RealtimeNotification>;

export const RealtimeActivity = z.object({
  "type": z.enum(["activity"]),
  "payload": z.object({
  "who": z.string().optional(),
  "what": z.string().optional(),
  "target": z.string().optional(),
  "verb": z.string().optional(),
  "time": z.string().optional(),
  "proj": z.string().optional(),
  "kind": z.string().optional()
})
});
export type RealtimeActivity = z.infer<typeof RealtimeActivity>;

export const RealtimePresence = z.object({
  "type": z.enum(["presence"]),
  "payload": z.object({
  "userId": z.string().optional(),
  "online": z.boolean().optional(),
  "lastSeen": z.string().optional()
})
});
export type RealtimePresence = z.infer<typeof RealtimePresence>;

export const RealtimeChat = z.object({
  "type": z.enum(["chat"]),
  "payload": z.object({
  "channelId": z.string().optional(),
  "messageId": z.string().optional(),
  "authorId": z.string().optional(),
  "text": z.string().optional(),
  "time": z.string().optional()
})
});
export type RealtimeChat = z.infer<typeof RealtimeChat>;

export const RealtimeEvent = z.discriminatedUnion('type', [RealtimeNotification, RealtimeActivity, RealtimePresence, RealtimeChat]);
export type RealtimeEvent = z.infer<typeof RealtimeEvent>;
