ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mfa_secret"   TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mfa_enabled"  BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mfa_recovery" TEXT[] NOT NULL DEFAULT '{}';
