// AUTO-GENERATED by packages/contracts/scripts/openapi-to-zod.mjs — DO NOT EDIT.
// Source: packages/contracts/openapi.yaml (SOR)
// Run `pnpm --filter @all-flow/contracts gen:zod` (or `pnpm --filter @all-flow/backend openapi:gen`) to regenerate.
// `pnpm --filter @all-flow/backend openapi:check` validates drift.

import { z } from 'zod';

export const StatusKey = z.enum(["todo", "doing", "review", "done", "blocked"]);
export type StatusKey = z.infer<typeof StatusKey>;

export const User = z.object({
  "id": z.string(),
  "name": z.string(),
  "role": z.string(),
  "dept": z.string(),
  "initials": z.string(),
  "color": z.string(),
  "email": z.string().email().optional()
});
export type User = z.infer<typeof User>;

export const Project = z.object({
  "id": z.string(),
  "name": z.string(),
  "code": z.string(),
  "color": z.string(),
  "progress": z.number().int().min(0).max(100),
  "status": StatusKey,
  "due": z.string().nullable(),
  "members": z.array(z.string()),
  "tasks": z.object({
  "total": z.number().int(),
  "done": z.number().int()
})
});
export type Project = z.infer<typeof Project>;

export const ProjectCreate = z.object({
  "name": z.string(),
  "code": z.string(),
  "color": z.string().optional(),
  "due": z.string().optional()
});
export type ProjectCreate = z.infer<typeof ProjectCreate>;

export const ProjectPatch = z.object({
  "name": z.string().optional(),
  "progress": z.number().int().optional(),
  "status": StatusKey.optional(),
  "due": z.string().optional()
});
export type ProjectPatch = z.infer<typeof ProjectPatch>;

export const TaskKind = z.enum(["task", "milestone", "summary"]);
export type TaskKind = z.infer<typeof TaskKind>;

export const Task = z.object({
  "id": z.string(),
  "title": z.string(),
  "status": StatusKey,
  "proj": z.string(),
  "assignee": z.string(),
  "due": z.string(),
  "priority": z.enum(["high", "med", "low"]),
  "tags": z.array(z.string()),
  "startDate": z.string().nullable().optional(),
  "endDate": z.string().nullable().optional(),
  "parentTaskId": z.string().nullable().optional(),
  "kind": TaskKind.optional(),
  "progress": z.number().int().min(0).max(100).optional()
});
export type Task = z.infer<typeof Task>;

export const TaskCreate = z.object({
  "title": z.string(),
  "proj": z.string(),
  "assignee": z.string(),
  "due": z.string().optional(),
  "priority": z.enum(["high", "med", "low"]).optional()
});
export type TaskCreate = z.infer<typeof TaskCreate>;

export const TaskPatch = z.object({
  "title": z.string().optional(),
  "status": StatusKey.optional(),
  "assignee": z.string().optional(),
  "due": z.string().optional(),
  "startDate": z.string().nullable().optional(),
  "endDate": z.string().nullable().optional(),
  "kind": TaskKind.optional(),
  "progress": z.number().int().min(0).max(100).optional()
});
export type TaskPatch = z.infer<typeof TaskPatch>;

export const DependencyType = z.enum(["FS", "SS", "FF", "SF"]);
export type DependencyType = z.infer<typeof DependencyType>;

export const TaskDependency = z.object({
  "id": z.string(),
  "predecessorId": z.string(),
  "successorId": z.string(),
  "type": DependencyType,
  "lagDays": z.number().int(),
  "createdAt": z.string().optional()
});
export type TaskDependency = z.infer<typeof TaskDependency>;

export const GanttTask = z.object({
  "id": z.string(),
  "title": z.string(),
  "kind": TaskKind,
  "projectId": z.string(),
  "projectColor": z.string().optional(),
  "assigneeId": z.string().nullable().optional(),
  "startDate": z.string().nullable().optional(),
  "endDate": z.string().nullable().optional(),
  "progress": z.number().int().min(0).max(100),
  "status": StatusKey,
  "priority": z.enum(["high", "med", "low"])
});
export type GanttTask = z.infer<typeof GanttTask>;

export const GanttResponse = z.object({
  "range": z.object({
  "from": z.string().optional(),
  "to": z.string().optional()
}).optional(),
  "tasks": z.array(GanttTask),
  "dependencies": z.array(TaskDependency)
});
export type GanttResponse = z.infer<typeof GanttResponse>;

export const GanttByAssignee = z.object({
  "groups": z.array(z.object({
  "assigneeId": z.string().nullable(),
  "assigneeName": z.string().nullable().optional(),
  "tasks": z.array(GanttTask),
  "conflictCount": z.number().int().min(0).optional()
}))
});
export type GanttByAssignee = z.infer<typeof GanttByAssignee>;

export const IssueSev = z.enum(["critical", "high", "med", "low"]);
export type IssueSev = z.infer<typeof IssueSev>;

export const IssuePrio = z.enum(["P0", "P1", "P2", "P3"]);
export type IssuePrio = z.infer<typeof IssuePrio>;

export const IssueStatus = z.enum(["open", "in-progress", "in-review", "resolved"]);
export type IssueStatus = z.infer<typeof IssueStatus>;

export const Issue = z.object({
  "id": z.string(),
  "title": z.string(),
  "proj": z.string(),
  "projColor": z.string(),
  "sev": IssueSev,
  "prio": IssuePrio,
  "status": IssueStatus,
  "assignee": z.string(),
  "reporter": z.string(),
  "tags": z.array(z.string()),
  "created": z.string(),
  "sla": z.string(),
  "slaPct": z.number().int(),
  "comments": z.number().int(),
  "linked": z.number().int(),
  "resolved": z.boolean().optional()
});
export type Issue = z.infer<typeof Issue>;

export const Report = z.object({
  "id": z.string(),
  "kind": z.enum(["weekly", "monthly"]),
  "periodStart": z.string(),
  "periodEnd": z.string(),
  "generatedAt": z.string(),
  "author": z.string().optional(),
  "tldr": z.string().optional(),
  "kpis": z.array(z.object({
  "label": z.string().optional(),
  "value": z.string().optional(),
  "delta": z.string().optional(),
  "dir": z.enum(["up", "down", "flat"]).optional()
})).optional(),
  "sections": z.array(z.object({
  "heading": z.string().optional(),
  "body": z.string().optional(),
  "citations": z.array(z.object({
  "kind": z.string().optional(),
  "id": z.string().optional(),
  "label": z.string().optional()
})).optional()
}))
});
export type Report = z.infer<typeof Report>;

export const ExtractedAction = z.object({
  "title": z.string(),
  "assignee": z.string(),
  "due": z.string().optional(),
  "priority": z.enum(["high", "med", "low"]).optional(),
  "confidence": z.number().min(0).max(1),
  "sourceQuote": z.string().optional()
});
export type ExtractedAction = z.infer<typeof ExtractedAction>;

export const LlmKind = z.enum(["lmstudio", "ollama", "openai", "anthropic", "custom_openai_compat"]);
export type LlmKind = z.infer<typeof LlmKind>;

export const LlmConnection = z.object({
  "id": z.string(),
  "name": z.string(),
  "kind": LlmKind,
  "baseUrl": z.string(),
  "model": z.string(),
  "hasApiKey": z.boolean(),
  "isActive": z.boolean(),
  "isDefault": z.boolean(),
  "createdAt": z.string(),
  "updatedAt": z.string()
});
export type LlmConnection = z.infer<typeof LlmConnection>;

export const LlmConnectionInput = z.object({
  "name": z.string(),
  "kind": LlmKind,
  "baseUrl": z.string(),
  "model": z.string(),
  "apiKey": z.string().optional()
});
export type LlmConnectionInput = z.infer<typeof LlmConnectionInput>;

export const Notification = z.object({
  "id": z.string(),
  "kind": z.enum(["mention", "sla", "ai", "system", "comment"]),
  "title": z.string(),
  "body": z.string().optional(),
  "actor": z.string().optional(),
  "time": z.string(),
  "read": z.boolean(),
  "href": z.string().optional()
});
export type Notification = z.infer<typeof Notification>;

export const RealtimeNotification = z.object({
  "type": z.enum(["notification"]),
  "payload": Notification
});
export type RealtimeNotification = z.infer<typeof RealtimeNotification>;

export const RealtimeActivity = z.object({
  "type": z.enum(["activity"]),
  "payload": z.object({
  "who": z.string().optional(),
  "what": z.string().optional(),
  "target": z.string().optional(),
  "verb": z.string().optional(),
  "time": z.string().optional(),
  "proj": z.string().optional(),
  "kind": z.string().optional()
})
});
export type RealtimeActivity = z.infer<typeof RealtimeActivity>;

export const RealtimePresence = z.object({
  "type": z.enum(["presence"]),
  "payload": z.object({
  "userId": z.string().optional(),
  "online": z.boolean().optional(),
  "lastSeen": z.string().optional()
})
});
export type RealtimePresence = z.infer<typeof RealtimePresence>;

export const RealtimeChat = z.object({
  "type": z.enum(["chat"]),
  "payload": z.object({
  "channelId": z.string().optional(),
  "messageId": z.string().optional(),
  "authorId": z.string().optional(),
  "text": z.string().optional(),
  "time": z.string().optional()
})
});
export type RealtimeChat = z.infer<typeof RealtimeChat>;

export const RealtimeEvent = z.discriminatedUnion('type', [RealtimeNotification, RealtimeActivity, RealtimePresence, RealtimeChat]);
export type RealtimeEvent = z.infer<typeof RealtimeEvent>;

export const Approval = z.object({
  "id": z.string(),
  "title": z.string(),
  "requester": z.string(),
  "approver": z.string(),
  "status": z.enum(["pending", "approved", "rejected", "cancelled"]),
  "amount": z.number().optional(),
  "reason": z.string().optional(),
  "decidedAt": z.string().optional(),
  "createdAt": z.string()
});
export type Approval = z.infer<typeof Approval>;

export const ApprovalCreate = z.object({
  "title": z.string(),
  "approver": z.string(),
  "amount": z.number().optional(),
  "reason": z.string().optional()
});
export type ApprovalCreate = z.infer<typeof ApprovalCreate>;

export const Client = z.object({
  "id": z.string(),
  "name": z.string(),
  "contact": z.string().optional(),
  "email": z.string().email().optional(),
  "phone": z.string().optional(),
  "industry": z.string().optional(),
  "ownerId": z.string().optional(),
  "createdAt": z.string()
});
export type Client = z.infer<typeof Client>;

export const ClientCreate = z.object({
  "name": z.string(),
  "contact": z.string().optional(),
  "email": z.string().email().optional(),
  "phone": z.string().optional(),
  "industry": z.string().optional()
});
export type ClientCreate = z.infer<typeof ClientCreate>;

export const Event = z.object({
  "id": z.string(),
  "title": z.string(),
  "start": z.string(),
  "end": z.string(),
  "location": z.string().optional(),
  "attendees": z.array(z.string()),
  "resourceId": z.string().optional(),
  "source": z.enum(["internal", "google", "outlook"])
});
export type Event = z.infer<typeof Event>;

export const EventCreate = z.object({
  "title": z.string(),
  "start": z.string(),
  "end": z.string(),
  "location": z.string().optional(),
  "attendees": z.array(z.string()).optional(),
  "resourceId": z.string().optional()
});
export type EventCreate = z.infer<typeof EventCreate>;

export const Resource = z.object({
  "id": z.string(),
  "name": z.string(),
  "kind": z.enum(["room", "equipment"]),
  "capacity": z.number().int().optional(),
  "location": z.string().optional()
});
export type Resource = z.infer<typeof Resource>;

export const ResourceBooking = z.object({
  "resourceId": z.string(),
  "start": z.string(),
  "end": z.string(),
  "bookedBy": z.string()
});
export type ResourceBooking = z.infer<typeof ResourceBooking>;

export const Doc = z.object({
  "id": z.string(),
  "title": z.string(),
  "ownerId": z.string(),
  "updatedAt": z.string(),
  "preview": z.string().optional()
});
export type Doc = z.infer<typeof Doc>;

export const Channel = z.object({
  "id": z.string(),
  "name": z.string(),
  "kind": z.enum(["public", "private", "dm"]),
  "members": z.array(z.string())
});
export type Channel = z.infer<typeof Channel>;

export const OrgUnit = z.object({
  "id": z.string(),
  "name": z.string(),
  "parentId": z.union([z.string(), z.unknown()]),
  "members": z.array(z.string())
});
export type OrgUnit = z.infer<typeof OrgUnit>;

export const IssueCreate = z.object({
  "title": z.string(),
  "proj": z.string(),
  "assignee": z.string(),
  "reporter": z.string(),
  "sev": IssueSev,
  "prio": IssuePrio,
  "tags": z.array(z.string()).optional()
});
export type IssueCreate = z.infer<typeof IssueCreate>;

export const Comment = z.object({
  "id": z.string(),
  "body": z.string(),
  "author": z.object({
  "id": z.string(),
  "name": z.string()
}),
  "createdAt": z.string()
});
export type Comment = z.infer<typeof Comment>;

export const CommentCreate = z.object({
  "body": z.string()
});
export type CommentCreate = z.infer<typeof CommentCreate>;
